services:
  postgresdb:
    image: postgres
    container_name: wongames_api
    environment:
      - POSTGRES_USER=strapi
      - POSTGRES_PASSWORD=strapi
      - POSTGRES_DB=strapi
    ports:
      - "5432:5432"
